name: pretty_logging
description: The pretty_logging library.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  intl: ^0.17.0
  lint:
    git:
      url: https://github.com/pro100andrey/lint.git
      ref: master
  logging: ^1.0.2

  